# Generated by Django 4.2.16 on 2024-09-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('specialist', models.TextField(null=True)),
                ('college', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=200)),
                ('restaurantType', models.TextField()),
                ('location', models.TextField()),
                ('chefName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_chef', to='restaurant_app.chef')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('restaurantName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_review', to='restaurant_app.restaurant')),
            ],
        ),
    ]
