# Generated by Django 4.2.16 on 2024-09-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('role', models.TextField(null=True)),
                ('qualification', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_Manager', to='restaurant_app.employees'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='waiters',
            field=models.ManyToManyField(related_name='restaurant_waiters', to='restaurant_app.employees'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='chefName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_chef', to='restaurant_app.employees'),
        ),
        migrations.DeleteModel(
            name='Chef',
        ),
    ]
