# Generated by Django 4.2.16 on 2024-09-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_alter_restaurant_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_Manager', to='restaurant_app.employees'),
        ),
    ]
